#pragma once

#include "GLFW/glfw3.h"

/* Printable keys */
#define	JERBOA_KEY_SPACE					GLFW_KEY_SPACE              
#define JERBOA_KEY_APOSTROPHE				GLFW_KEY_APOSTROPHE          
#define JERBOA_KEY_COMMA					GLFW_KEY_COMMA               
#define JERBOA_KEY_MINUS					GLFW_KEY_MINUS               
#define JERBOA_KEY_PERIOD					GLFW_KEY_PERIOD              
#define JERBOA_KEY_SLASH					GLFW_KEY_SLASH               
#define JERBOA_KEY_0						GLFW_KEY_0                  
#define JERBOA_KEY_1						GLFW_KEY_1                  
#define JERBOA_KEY_2						GLFW_KEY_2                  
#define JERBOA_KEY_3						GLFW_KEY_3                  
#define JERBOA_KEY_4						GLFW_KEY_4                  
#define JERBOA_KEY_5						GLFW_KEY_5                  
#define JERBOA_KEY_6						GLFW_KEY_6                  
#define JERBOA_KEY_7						GLFW_KEY_7                  
#define JERBOA_KEY_8						GLFW_KEY_8                  
#define JERBOA_KEY_9						GLFW_KEY_9                  
#define JERBOA_KEY_SEMICOLON				GLFW_KEY_SEMICOLON           
#define JERBOA_KEY_EQUAL					GLFW_KEY_EQUAL               
#define JERBOA_KEY_A						GLFW_KEY_A                  
#define JERBOA_KEY_B						GLFW_KEY_B                  
#define JERBOA_KEY_C						GLFW_KEY_C                  
#define JERBOA_KEY_D						GLFW_KEY_D                  
#define JERBOA_KEY_E						GLFW_KEY_E                  
#define JERBOA_KEY_F						GLFW_KEY_F                  
#define JERBOA_KEY_G						GLFW_KEY_G                  
#define JERBOA_KEY_H						GLFW_KEY_H                  
#define JERBOA_KEY_I						GLFW_KEY_I                  
#define JERBOA_KEY_J						GLFW_KEY_J                  
#define JERBOA_KEY_K						GLFW_KEY_K                  
#define JERBOA_KEY_L						GLFW_KEY_L                  
#define JERBOA_KEY_M						GLFW_KEY_M                  
#define JERBOA_KEY_N						GLFW_KEY_N                  
#define JERBOA_KEY_O						GLFW_KEY_O                  
#define JERBOA_KEY_P						GLFW_KEY_P                  
#define JERBOA_KEY_Q						GLFW_KEY_Q                  
#define JERBOA_KEY_R						GLFW_KEY_R                  
#define JERBOA_KEY_S						GLFW_KEY_S                  
#define JERBOA_KEY_T						GLFW_KEY_T                  
#define JERBOA_KEY_U						GLFW_KEY_U                  
#define JERBOA_KEY_V						GLFW_KEY_V                  
#define JERBOA_KEY_W						GLFW_KEY_W                  
#define JERBOA_KEY_X						GLFW_KEY_X                  
#define JERBOA_KEY_Y						GLFW_KEY_Y                  
#define JERBOA_KEY_Z						GLFW_KEY_Z                  
#define JERBOA_KEY_LEFT_BRACKET				GLFW_KEY_LEFT_BRACKET        
#define JERBOA_KEY_BACKSLASH				GLFW_KEY_BACKSLASH           
#define JERBOA_KEY_RIGHT_BRACKET			GLFW_KEY_RIGHT_BRACKET       
#define JERBOA_KEY_GRAVE_ACCENT				GLFW_KEY_GRAVE_ACCENT        
#define JERBOA_KEY_WORLD_1					GLFW_KEY_WORLD_1             
#define JERBOA_KEY_WORLD_2					GLFW_KEY_WORLD_2             

/* Functkeys */
#define JERBOA_KEY_ESCAPE					GLFW_KEY_ESCAPE             
#define JERBOA_KEY_ENTER					GLFW_KEY_ENTER              
#define JERBOA_KEY_TAB						GLFW_KEY_TAB                
#define JERBOA_KEY_BACKSPACE				GLFW_KEY_BACKSPACE          
#define JERBOA_KEY_INSERT					GLFW_KEY_INSERT             
#define JERBOA_KEY_DELETE					GLFW_KEY_DELETE             
#define JERBOA_KEY_RIGHT					GLFW_KEY_RIGHT              
#define JERBOA_KEY_LEFT						GLFW_KEY_LEFT               
#define JERBOA_KEY_DOWN						GLFW_KEY_DOWN               
#define JERBOA_KEY_UP						GLFW_KEY_UP                 
#define JERBOA_KEY_PAGE_UP					GLFW_KEY_PAGE_UP            
#define JERBOA_KEY_PAGE_DOWN				GLFW_KEY_PAGE_DOWN          
#define JERBOA_KEY_HOME						GLFW_KEY_HOME               
#define JERBOA_KEY_END						GLFW_KEY_END                
#define JERBOA_KEY_CAPS_LOCK				GLFW_KEY_CAPS_LOCK          
#define JERBOA_KEY_SCROLL_LOCK				GLFW_KEY_SCROLL_LOCK        
#define JERBOA_KEY_NUM_LOCK					GLFW_KEY_NUM_LOCK           
#define JERBOA_KEY_PRINT_SCREEN				GLFW_KEY_PRINT_SCREEN       
#define JERBOA_KEY_PAUSE					GLFW_KEY_PAUSE              
#define JERBOA_KEY_F1						GLFW_KEY_F1                 
#define JERBOA_KEY_F2						GLFW_KEY_F2                 
#define JERBOA_KEY_F3						GLFW_KEY_F3                 
#define JERBOA_KEY_F4						GLFW_KEY_F4                 
#define JERBOA_KEY_F5						GLFW_KEY_F5                 
#define JERBOA_KEY_F6						GLFW_KEY_F6                 
#define JERBOA_KEY_F7						GLFW_KEY_F7                 
#define JERBOA_KEY_F8						GLFW_KEY_F8                 
#define JERBOA_KEY_F9						GLFW_KEY_F9                 
#define JERBOA_KEY_F10						GLFW_KEY_F10                
#define JERBOA_KEY_F11						GLFW_KEY_F11                
#define JERBOA_KEY_F12						GLFW_KEY_F12                
#define JERBOA_KEY_F13						GLFW_KEY_F13                
#define JERBOA_KEY_F14						GLFW_KEY_F14                
#define JERBOA_KEY_F15						GLFW_KEY_F15                
#define JERBOA_KEY_F16						GLFW_KEY_F16                
#define JERBOA_KEY_F17						GLFW_KEY_F17                
#define JERBOA_KEY_F18						GLFW_KEY_F18                
#define JERBOA_KEY_F19						GLFW_KEY_F19                
#define JERBOA_KEY_F20						GLFW_KEY_F20                
#define JERBOA_KEY_F21						GLFW_KEY_F21                
#define JERBOA_KEY_F22						GLFW_KEY_F22                
#define JERBOA_KEY_F23						GLFW_KEY_F23                
#define JERBOA_KEY_F24						GLFW_KEY_F24                
#define JERBOA_KEY_F25						GLFW_KEY_F25                
#define JERBOA_KEY_KP_0						GLFW_KEY_KP_0               
#define JERBOA_KEY_KP_1						GLFW_KEY_KP_1               
#define JERBOA_KEY_KP_2						GLFW_KEY_KP_2               
#define JERBOA_KEY_KP_3						GLFW_KEY_KP_3               
#define JERBOA_KEY_KP_4						GLFW_KEY_KP_4               
#define JERBOA_KEY_KP_5						GLFW_KEY_KP_5               
#define JERBOA_KEY_KP_6						GLFW_KEY_KP_6               
#define JERBOA_KEY_KP_7						GLFW_KEY_KP_7               
#define JERBOA_KEY_KP_8						GLFW_KEY_KP_8               
#define JERBOA_KEY_KP_9						GLFW_KEY_KP_9               
#define JERBOA_KEY_KP_DECIMAL				GLFW_KEY_KP_DECIMAL         
#define JERBOA_KEY_KP_DIVIDE				GLFW_KEY_KP_DIVIDE          
#define JERBOA_KEY_KP_MULTIPLY				GLFW_KEY_KP_MULTIPLY        
#define JERBOA_KEY_KP_SUBTRACT				GLFW_KEY_KP_SUBTRACT        
#define JERBOA_KEY_KP_ADD					GLFW_KEY_KP_ADD             
#define JERBOA_KEY_KP_ENTER					GLFW_KEY_KP_ENTER           
#define JERBOA_KEY_KP_EQUAL					GLFW_KEY_KP_EQUAL           
#define JERBOA_KEY_LEFT_SHIFT				GLFW_KEY_LEFT_SHIFT         
#define JERBOA_KEY_LEFT_CONTROL				GLFW_KEY_LEFT_CONTROL       
#define JERBOA_KEY_LEFT_ALT					GLFW_KEY_LEFT_ALT           
#define JERBOA_KEY_LEFT_SUPER				GLFW_KEY_LEFT_SUPER         
#define JERBOA_KEY_RIGHT_SHIFT				GLFW_KEY_RIGHT_SHIFT        
#define JERBOA_KEY_RIGHT_CONTROL			GLFW_KEY_RIGHT_CONTROL      
#define JERBOA_KEY_RIGHT_ALT				GLFW_KEY_RIGHT_ALT          
#define JERBOA_KEY_RIGHT_SUPER				GLFW_KEY_RIGHT_SUPER        
#define JERBOA_KEY_MENU						GLFW_KEY_MENU               